Twaha-Rahman/e-commercify

- package-lock.json
- package.json
- src/main.js
- src/schemas/graphql-schema.js
- src/schemas/graphql/ProductType.js
This PR adds a basic GraphQL API, which will act as the building block of the API
> Add basic GraphQL API

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a bug report and feature request template for issues, and a base template for new PRs. 
Closes #2
> Create Issue templates and PR templates

- src/schemas/db/productSchema.js
Fixed the linting issue with the long line. @magnus195 's PR added a long Regex that breaks ESLints long line rule, which was fixed in this PR
> Fixed the linting issue with the long line

- src/models/db/discount.js
- src/models/db/product.js
- src/schemas/db/discountSchema.js
- src/schemas/db/productSchema.js
I have changed the files to only import Schema or model, and not everything in mongoose
**Additional Information**
It's supposed to lower memory usage. I don't know if it works but if we try to scale and stress test then we'll know.
> Simplified schemas and models

- Docs/BACKEND_API.md
- sampleDBData.js
- src/schemas/db/discountSchema.js
- src/schemas/db/productSchema.js
- src/schemas/graphql/ProductType.js
This PR fixes inconsistency in backend docs
> Fix inconsistency in backend docs

- sampleDBData.js
- src/schemas/db/productSchema.js
This just converts the string into a RegExp
**Related Issue**
Closes #26 
**Additional Information**
I also simplified the sample data script a tiny bit
> Fixed a bug (RegExp.test is not a function)

- package.json
> Enable linting .js files before commits

- Docs/BACKEND_API.md
- sampleDBData.js
- src/schemas/db/productSchema.js
- src/schemas/graphql-schema.js
- src/schemas/graphql/ProductType.js
> Rename productName field to name

- CONTRIBUTING.md
- README.md
- package.json
- sample-data/sampleProductData.json
- sample.env
- src/schemas/db/productSchema.js
- tools/sampleDBData.js
- tools/sampleDBDataInjector.js
This PR refactors and organizes the tools for the project.
Closes #29
> Organize tools

- Docs/BACKEND_API.md
- sampleDBData.js
- src/schemas/db/productSchema.js
- src/schemas/graphql/ProductType.js
> Rename the productImageLinks field to imageLinks

- LICENSE
- package.json
Added the license for the `E-commercify` project.
> Added MIT License

- .github/workflows/stale.yml
Just added a workflow bot that'll label issues/PRs inactive if they are inactive for a while.
> Updated the message for stale PR/issues

- src/main.js
> Refactor main.js to use async/await

- .gitpod.Dockerfile
- .gitpod.yml
- sample.env
Added a basic GitPod setup and a dockerfile for GitPod.
**Related Issue**
Closes #47 
**Additional Information**
> Add basic gitpod support

- CONTRIBUTING.md
- README.md
Added Gitpod reference in the both README and CONTRIBUTING files. added some badges and ordered them correctly. Moved running the server to the CONTRIBUTING file. Added Gitpod at the beginning of README to preview the progress of the project.
> Update the README and CONTRIBUTING to re-organize it

- Docs/BACKEND_API.md
- sample-data/sampleBannerData.json
- src/schemas/db/bannerSchema.js
- src/schemas/graphql-schema.js
- src/schemas/graphql/MutationResponseType.js
Connected the banner endpoint with database.
> Connect banner endpoint with db

- tools/sampleDBDataInjector.js
This PR injects `bannerId` key in the sample banner data.
**Related Issue**
Related to #68
> Add support for bannerId in sampledatainjector

- Docs/BACKEND_API.md
- sample-data/sampleReviewData.json
- src/modules/connect-to-mongodb.js
- src/modules/get-ip-address.js
- src/schemas/db/reviewSchema.js
- src/schemas/graphql-schema.js
- tests/reviewModel.test.js
- tools/sampleDBDataInjector.js
Added the mutation endpoints for reviews.
> Create review mutation endpoints

- src/models/db/system-log.js
- src/modules/connect-to-mongodb.js
- src/modules/log-formatter.js
- src/modules/logger.js
- src/schemas/db/system-log-schema.js
- tools/sampleDBDataInjector.js
This PR adds the `logger` module that'll be used for centralized logging. The benefits are described in the #86 
Does it close an issue? Does it connect to an issue?
Closes #86
> Add centralized logging module (logger)

- src/main.js
- src/modules/cli-argument-parse.js
- src/modules/connect-to-mongodb.js
- src/modules/log-formatter.js
- src/modules/paginate.js
- src/placeholder.js
- src/schemas/db/bannerSchema.js
- src/schemas/graphql-schema.js
- src/schemas/graphql/BannerType.js
- src/schemas/graphql/MutationResponseType.js
- src/schemas/graphql/ProductType.js
- src/schemas/graphql/ReviewType.js
- tests/sum.test.js
> Use JsDoc file overviews in every JavaScript file

- package-lock.json
- package.json
- src/main.js
Integrate Helmet using the default configuration for now.
**Related Issue**
Related to #84
> Integrate Helmet

- sample-data/sampleBannerData.json
- src/models/db/activity.js
- src/schemas/db/activitySchema.js
- src/schemas/db/bannerSchema.js
- src/schemas/db/productSchema.js
- tests/activityLogModel.test.js
- tests/bannerModel.test.js
- tests/productModel.test.js
- tests/reviewModel.test.js
- tests/systemLogSchema.test.js
This PR adds tests for all the Mongoose models that are currently available.
(Unit test with Jest)
> Add tests for all models

- .github/workflows/lighthouse-ci.yml
- lighthouserc.js
Adds LightHouse to the CI pipeline.
> Added basic LHCI config
